/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  tutorialSidebar: [
    {
      type: "autogenerated",
      dirName: ".", // '.' means the current docs folder
    },
    {},
  ],
  apiSidebar: ["category/cat/commonDoc", "category/intro"],
  // apiSidebar: ["category/cat/commonDoc", "category/intro"],
  tutorial4: [
    "docs2/intro",
    "docs2/cat/peter",
    "docs2/cat/peter3",
    "docs2/cat2/peter2",
  ],
  // But you can create a sidebar manually
};

module.exports = sidebars;
